"""Turn the JSON produced by the pipeline into LaTeX the report can \\input.

    python reports/build_report_data.py

Reads everything under ``artifacts/results/`` and writes
``reports/final_report/generated/``:

    macros.tex      \\newcommand definitions for every inline number
    tab_dataset.tex     corpus statistics
    tab_model.tex       architecture and parameter counts
    tab_results.tex     BLEU / chrF per system and direction
    tab_errors.tex      failure-mode census
    tab_examples.tex    the twenty worst translations, for the appendix

Why this exists: a number that is typed into a report by hand goes stale the
moment a model is retrained, and there is no way to tell from the document
whether it did. Generating the tables means the report always agrees with the
artefacts in the repository, and re-running one command after a new training
run refreshes every figure and table at once.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

from nmt.constants import DIRECTIONS
from nmt.utils.io import ensure_dir, project_root, read_json
from nmt.utils.logging_utils import get_logger, setup_logging

logger = get_logger(__name__)

RUN_LABELS = {
    "bpe_scratch": "BPE 16k, learned embeddings",
    "word_random": "Word 32k, random init",
    "word_muse": "Word 32k, MUSE init",
    "lstm_baseline": "LSTM + Bahdanau attention",
}
RUN_ORDER = ["bpe_scratch", "word_random", "word_muse", "lstm_baseline"]


def tex_escape(text: str) -> str:
    """Escape the characters LaTeX would otherwise interpret."""
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&", "%": r"\%", "$": r"\$", "#": r"\#",
        "_": r"\_", "{": r"\{", "}": r"\}",
        "~": r"\textasciitilde{}", "^": r"\textasciicircum{}",
        "<": r"\textless{}", ">": r"\textgreater{}",
    }
    return "".join(replacements.get(character, character) for character in text)


def macro_name(key: str) -> str:
    """Turn a snake_case key into a LaTeX-legal command name (letters only)."""
    words = re.split(r"[^a-zA-Z0-9]+", key)
    digits = {"0": "Zero", "1": "One", "2": "Two", "3": "Three", "4": "Four",
              "5": "Five", "6": "Six", "7": "Seven", "8": "Eight", "9": "Nine"}
    name = "".join(word.capitalize() for word in words if word)
    return "".join(digits.get(character, character) for character in name)


class MacroFile:
    """Accumulates ``\\newcommand`` definitions."""

    def __init__(self) -> None:
        self.entries: dict[str, str] = {}

    def add(self, key: str, value: object, *, fmt: str = "{}") -> None:
        self.entries[macro_name(key)] = fmt.format(value)

    def number(self, key: str, value: float, *, decimals: int = 2) -> None:
        self.add(key, f"{value:,.{decimals}f}")

    def integer(self, key: str, value: int) -> None:
        self.add(key, f"{value:,}")

    def render(self) -> str:
        lines = [
            "% Generated by reports/build_report_data.py -- do not edit by hand.",
            "% Every number quoted inline in the report comes from here, so the",
            "% prose cannot drift out of step with the artefacts in the repo.",
            "",
        ]
        for name in sorted(self.entries):
            lines.append(f"\\newcommand{{\\{name}}}{{{self.entries[name]}}}")
        return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Tables
# ---------------------------------------------------------------------------


def dataset_table(stats: dict, macros: MacroFile) -> str:
    splits = stats["splits"]
    rows = []
    for name in ("train", "validation", "test"):
        entry = splits[name]
        rows.append(
            f"{name.capitalize()} & {entry['pairs']:,} & "
            f"{entry['unique_en']:,} & {entry['unique_es']:,} & "
            f"{entry['length_words']['en']['mean']:.1f} & "
            f"{entry['length_words']['es']['mean']:.1f} & "
            f"{entry['length_subwords']['en']['mean']:.1f} & "
            f"{entry['length_subwords']['es']['mean']:.1f} \\\\"
        )
        macros.integer(f"pairs {name}", entry["pairs"])

    pairing = stats.get("pairing", {})
    cleaning = stats.get("cleaning", {})
    split = stats.get("split", {})

    macros.integer("tatoeba english sentences", pairing.get("english_sentences", 0))
    macros.integer("tatoeba spanish sentences", pairing.get("spanish_sentences", 0))
    macros.integer("tatoeba links scanned", pairing.get("links_scanned", 0))
    macros.integer("pairs raw", pairing.get("pairs_found", 0))
    macros.integer("pairs clean", cleaning.get("kept_pairs", 0))
    macros.number("retention percent", cleaning.get("retention_rate", 0) * 100, decimals=2)
    macros.integer("components", split.get("components", 0))
    macros.integer("leakage", sum(split.get("leakage_check", {}).values()))
    macros.integer("largest component", split.get("largest_component_pairs", 0))

    vocabulary = splits["train"]["vocabulary"]
    macros.integer("types en", vocabulary["en"]["types"])
    macros.integer("types es", vocabulary["es"]["types"])
    macros.number("type ratio", vocabulary["es"]["types"] / vocabulary["en"]["types"])
    macros.integer("tokens en", vocabulary["en"]["tokens"])
    macros.integer("tokens es", vocabulary["es"]["tokens"])
    macros.number("hapax en percent", vocabulary["en"]["hapax_fraction"] * 100, decimals=1)
    macros.number("hapax es percent", vocabulary["es"]["hapax_fraction"] * 100, decimals=1)

    oov = splits["test"]["word_oov"]
    macros.number("oov en percent", oov["en"]["unk_rate"] * 100, decimals=2)
    macros.number("oov es percent", oov["es"]["unk_rate"] * 100, decimals=2)

    macros.number("fertility en", splits["train"]["subword_fertility"]["en"])
    macros.number("fertility es", splits["train"]["subword_fertility"]["es"])
    macros.integer("subword vocab", stats["tokenizers"]["subword"]["vocab_size"])
    macros.integer("word vocab", stats["tokenizers"]["word"]["vocab_size"])

    return (
        "\\begin{tabular}{lrrrrrrr}\n"
        "\\toprule\n"
        "& & \\multicolumn{2}{c}{unique sentences} & "
        "\\multicolumn{2}{c}{mean words} & \\multicolumn{2}{c}{mean subwords} \\\\\n"
        "\\cmidrule(lr){3-4}\\cmidrule(lr){5-6}\\cmidrule(lr){7-8}\n"
        "Split & Pairs & EN & ES & EN & ES & EN & ES \\\\\n"
        "\\midrule\n" + "\n".join(rows) + "\n"
        "\\bottomrule\n"
        "\\end{tabular}\n"
    )


def model_table(summaries: dict[str, dict], macros: MacroFile) -> str:
    rows = []
    for run in RUN_ORDER:
        summary = summaries.get(run)
        if not summary:
            continue
        config = summary["config"]["model"]
        parameters = summary["parameters"]["total"]
        macros.integer(f"params {run}", parameters)
        macros.add(f"epochs {run}", summary.get("epochs_completed", "--"))

        if config["architecture"] == "transformer":
            geometry = (
                f"{config['num_encoder_layers']}+{config['num_decoder_layers']} layers, "
                f"$d_{{\\mathrm{{model}}}}={config['d_model']}$, "
                f"{config['num_heads']} heads"
            )
        else:
            geometry = (
                f"{config['lstm_num_layers']} layers, "
                f"hidden {config['lstm_hidden_size']}, bi-encoder"
            )

        rows.append(
            f"{RUN_LABELS.get(run, run)} & {config['vocab_size']:,} & "
            f"{config.get('embedding_dim') or config['d_model']} & "
            f"{geometry} & {parameters / 1e6:.1f}M \\\\"
        )

    if not rows:
        rows = ["\\multicolumn{5}{c}{\\itshape no trained runs found} \\\\"]

    return (
        "\\begin{tabular}{lrrlr}\n"
        "\\toprule\n"
        "System & Vocab & Emb. dim & Geometry & Params \\\\\n"
        "\\midrule\n" + "\n".join(rows) + "\n"
        "\\bottomrule\n"
        "\\end{tabular}\n"
    )


def results_table(reports: dict[str, dict], macros: MacroFile) -> str:
    rows = []
    for run in RUN_ORDER:
        report = reports.get(run)
        if not report:
            continue
        summary = report["summary"]
        values = []
        for direction in DIRECTIONS:
            bleu = summary["bleu"][direction]
            chrf = summary["chrf2"][direction]
            values.extend([f"{bleu:.2f}", f"{chrf:.2f}"])
            macros.number(f"bleu {run} {direction}", bleu)
            macros.number(f"chrf {run} {direction}", chrf)
        macros.number(f"bleu {run} mean", summary["mean_bleu"])
        rows.append(f"{RUN_LABELS.get(run, run)} & " + " & ".join(values) +
                    f" & {summary['mean_bleu']:.2f} \\\\")

    if not rows:
        rows = ["\\multicolumn{6}{c}{\\itshape no evaluations found} \\\\"]

    return (
        "\\begin{tabular}{lrrrrr}\n"
        "\\toprule\n"
        "& \\multicolumn{2}{c}{EN $\\rightarrow$ ES} & "
        "\\multicolumn{2}{c}{ES $\\rightarrow$ EN} & \\\\\n"
        "\\cmidrule(lr){2-3}\\cmidrule(lr){4-5}\n"
        "System & BLEU & chrF2 & BLEU & chrF2 & Mean BLEU \\\\\n"
        "\\midrule\n" + "\n".join(rows) + "\n"
        "\\bottomrule\n"
        "\\end{tabular}\n"
    )


def error_table(report: dict, macros: MacroFile, run: str) -> str:
    categories: dict[str, dict[str, float]] = {}
    for direction in DIRECTIONS:
        analysis = report["directions"][direction]["error_analysis"]
        for name, rate in analysis["category_rates"].items():
            categories.setdefault(name, {})[direction] = rate * 100
        macros.number(
            f"mean sentence bleu {run} {direction}", analysis["mean_sentence_bleu"]
        )

    rows = []
    for name in sorted(categories, key=lambda n: -sum(categories[n].values())):
        values = " & ".join(
            f"{categories[name].get(direction, 0.0):.1f}\\%" for direction in DIRECTIONS
        )
        rows.append(f"\\texttt{{{tex_escape(name)}}} & {values} \\\\")
        for direction in DIRECTIONS:
            macros.number(
                f"error {run} {name} {direction}",
                categories[name].get(direction, 0.0), decimals=1,
            )

    if not rows:
        rows = ["\\multicolumn{3}{c}{\\itshape none} \\\\"]

    return (
        "\\begin{tabular}{lrr}\n"
        "\\toprule\n"
        "Failure mode & EN $\\rightarrow$ ES & ES $\\rightarrow$ EN \\\\\n"
        "\\midrule\n" + "\n".join(rows) + "\n"
        "\\bottomrule\n"
        "\\end{tabular}\n"
    )


def examples_table(report: dict, limit: int = 20) -> str:
    """The worst translations, formatted as a longtable for the appendix."""
    blocks = []
    for direction in DIRECTIONS:
        analysis = report["directions"][direction]["error_analysis"]
        arrow = ("EN $\\rightarrow$ ES" if direction == "en-es"
                 else "ES $\\rightarrow$ EN")
        rows = []
        for index, example in enumerate(analysis["worst"][:limit], start=1):
            rows.append(
                f"{index} & {example['sentence_bleu']:.1f} & "
                f"\\small {tex_escape(example['source'])} \\\\\n"
                f"& & \\small\\itshape ref: {tex_escape(example['reference'])} \\\\\n"
                f"& & \\small\\ttfamily out: {tex_escape(example['hypothesis'])} \\\\\n"
                f"& & \\scriptsize {tex_escape(', '.join(example['categories']))} \\\\"
                "\\addlinespace"
            )
        blocks.append(
            f"\\subsection*{{{arrow}}}\n"
            "\\begin{longtable}{@{}rp{0.7cm}p{11cm}@{}}\n"
            "\\toprule\n"
            "\\# & sBLEU & Source / reference / model output / failure modes \\\\\n"
            "\\midrule\n\\endhead\n" + "\n".join(rows) + "\n"
            "\\bottomrule\n\\end{longtable}\n"
        )
    return "\n".join(blocks)


# ---------------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------------


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--results", type=Path, default=None)
    parser.add_argument("--output", type=Path, default=None)
    parser.add_argument(
        "--primary", default="bpe_scratch",
        help="run whose error analysis and examples go in the appendix",
    )
    args = parser.parse_args()

    setup_logging()
    root = project_root()
    results_dir = args.results or root / "artifacts" / "results"
    output_dir = ensure_dir(args.output or root / "reports" / "final_report" / "generated")

    macros = MacroFile()

    # --- dataset ----------------------------------------------------------
    stats_path = results_dir / "dataset_stats.json"
    if stats_path.exists():
        stats = read_json(stats_path)
        (output_dir / "tab_dataset.tex").write_text(
            dataset_table(stats, macros), encoding="utf-8"
        )
        logger.info("tab_dataset.tex")
    else:
        logger.warning("No dataset_stats.json; run `python -m nmt.data.build` first.")

    # --- embedding coverage ----------------------------------------------
    embedding_path = results_dir / "embedding_init_report.json"
    if embedding_path.exists():
        report = read_json(embedding_path)
        macros.number("muse coverage percent", report["covered_fraction"] * 100, decimals=1)
        macros.integer("muse covered", report["covered"])
        macros.integer("muse random", report["randomly_initialised"])

    # --- models and training ---------------------------------------------
    summaries: dict[str, dict] = {}
    reports: dict[str, dict] = {}
    for directory in sorted(p for p in results_dir.iterdir() if p.is_dir()):
        summary_path = directory / "training_summary.json"
        if summary_path.exists():
            summary = read_json(summary_path)
            if summary.get("history"):
                summaries[directory.name] = summary
        evaluation_path = directory / "evaluation_test.json"
        if evaluation_path.exists():
            reports[directory.name] = read_json(evaluation_path)

    (output_dir / "tab_model.tex").write_text(
        model_table(summaries, macros), encoding="utf-8"
    )
    (output_dir / "tab_results.tex").write_text(
        results_table(reports, macros), encoding="utf-8"
    )
    logger.info("tab_model.tex, tab_results.tex (%d runs, %d evaluations)",
                len(summaries), len(reports))

    primary = args.primary if args.primary in reports else (
        next(iter(reports), None)
    )
    if primary:
        (output_dir / "tab_errors.tex").write_text(
            error_table(reports[primary], macros, primary), encoding="utf-8"
        )
        (output_dir / "tab_examples.tex").write_text(
            examples_table(reports[primary]), encoding="utf-8"
        )
        macros.add("primary run", tex_escape(RUN_LABELS.get(primary, primary)))
        logger.info("tab_errors.tex, tab_examples.tex (from %s)", primary)
    else:
        for name in ("tab_errors.tex", "tab_examples.tex"):
            (output_dir / name).write_text(
                "\\textit{No evaluation results available yet.}\n", encoding="utf-8"
            )
        logger.warning("No evaluation reports; wrote placeholder tables.")

    # A single flag the report uses to switch between "results pending" and the
    # real discussion, so the document always compiles.
    macros.add("has results", "true" if reports else "false")

    (output_dir / "macros.tex").write_text(macros.render(), encoding="utf-8")
    logger.info("macros.tex (%d macros) -> %s", len(macros.entries), output_dir)


if __name__ == "__main__":
    main()
