"""Generate the project notebooks from a compact specification.

    python notebooks/_build_notebooks.py

The notebooks are kept in source control with their outputs stripped, so they
are readable in a diff and small in the repository. Writing them from a script
means the shared boilerplate (path setup, styling, imports) is defined once and
cannot drift between notebooks.

Run the notebooks themselves to populate the outputs; do not edit this file to
change a result.
"""

from __future__ import annotations

import json
from pathlib import Path

HERE = Path(__file__).resolve().parent

#: Prepended to every notebook so `import nmt` works when Jupyter is launched
#: from any directory.
BOOTSTRAP = """import sys
from pathlib import Path

ROOT = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
sys.path.insert(0, str(ROOT / "src"))

from nmt.utils.io import project_root, read_json
from nmt.viz.style import use_style

use_style()
print("project root:", ROOT)"""


def _cell_id() -> str:
    """Stable-enough unique id; nbformat >= 4.5 requires one per cell."""
    global _COUNTER
    _COUNTER += 1
    return f"cell-{_COUNTER:03d}"


_COUNTER = 0


def markdown(text: str) -> dict:
    return {
        "cell_type": "markdown",
        "id": _cell_id(),
        "metadata": {},
        "source": text.splitlines(True),
    }


def code(text: str) -> dict:
    return {
        "cell_type": "code",
        "id": _cell_id(),
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": text.splitlines(True),
    }


def notebook(cells: list[dict]) -> dict:
    return {
        "cells": cells,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            },
            "language_info": {"name": "python", "version": "3.10"},
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }


# ---------------------------------------------------------------------------
# 01 — data exploration
# ---------------------------------------------------------------------------

NB01 = [
    markdown("""# 1 — Data collection and exploration

**AIG230 Final Project · Group 7**

The corpus is rebuilt from the official Tatoeba exports rather than downloaded
as a ready-made bitext, so that we control the snapshot and keep the sentence
ids for traceability.

If `artifacts/results/dataset_stats.json` does not exist yet, run:

```bash
python -m nmt.data.build
```
"""),
    code(BOOTSTRAP),
    code("""stats = read_json(ROOT / "artifacts" / "results" / "dataset_stats.json")
pairing, cleaning, split = stats["pairing"], stats["cleaning"], stats["split"]

print(f"English sentences in Tatoeba : {pairing['english_sentences']:,}")
print(f"Spanish sentences            : {pairing['spanish_sentences']:,}")
print(f"Translation links scanned    : {pairing['links_scanned']:,}")
print(f"EN-ES pairs recovered        : {pairing['pairs_found']:,}")
print(f"Pairs after cleaning         : {cleaning['kept_pairs']:,} "
      f"({cleaning['retention_rate']:.2%} retained)")"""),
    markdown("""## Why so little is removed

Tatoeba is human-curated, so the aggressive cleaning that web-crawled corpora
need is unnecessary here. The filters earn their place by *confirming* data
quality and by catching the handful of genuinely broken rows."""),
    code("""import pandas as pd

removed = pd.Series(cleaning["removed"], name="pairs removed").sort_values(ascending=False)
display(removed.to_frame())

for reason, examples in list(cleaning["examples_removed"].items())[:4]:
    print(f"\\n--- {reason} ---")
    for en, es in examples[:2]:
        print(f"  EN: {en}\\n  ES: {es}")"""),
    markdown("""## Splits, and the leakage that a naive split would cause

Tatoeba is a translation **graph**: one English sentence links to several
Spanish ones. Splitting the pair list at random puts paraphrases of the same
sentence on both sides of the train/test boundary. We split connected
components instead."""),
    code("""print("split sizes      :", split["split_pairs"])
print("components       :", f"{split['components']:,}")
print("largest component:", split["largest_component_pairs"], "pairs")
print("singletons       :", f"{split['singleton_components']:,}")
print()
print("Leakage check (sentences shared between splits):")
for key, value in split["leakage_check"].items():
    print(f"  {key:32s} {value}")"""),
    code("""# Demonstrate the failure the component split prevents.
import random
from nmt.data.build import read_split

train_pairs = read_split(ROOT / "data" / "processed" / "train.tsv")

from collections import Counter
english_counts = Counter(en for en, _ in train_pairs)
multi = [s for s, n in english_counts.most_common(5)]
print("English sentences with the most alternative Spanish translations:\\n")
for sentence in multi[:3]:
    print(f"  {sentence!r}  ->  {english_counts[sentence]} translations")
    for en, es in train_pairs:
        if en == sentence:
            print(f"        {es}")
    print()"""),
    markdown("## Length distributions"),
    code("""from nmt.viz.data_plots import plot_length_distributions

plot_length_distributions(ROOT / "data" / "processed", ROOT / "reports" / "figures" / "data_lengths")
from IPython.display import Image
Image(str(ROOT / "reports" / "figures" / "data_lengths.png"), width=900)"""),
    markdown("""## Vocabulary: the case for subword tokenisation

Spanish marks person, number, tense and mood on the verb, agrees adjectives and
articles for gender and number, and attaches clitic pronouns to infinitives.
English does almost none of this — so Spanish contributes far more distinct
surface forms for the same amount of running text."""),
    code("""vocab = stats["splits"]["train"]["vocabulary"]
summary = pd.DataFrame({
    lang: {
        "types": v["types"],
        "tokens": v["tokens"],
        "type/token ratio": round(v["type_token_ratio"], 4),
        "hapax %": round(100 * v["hapax_fraction"], 1),
        "coverage @10k": round(100 * v["coverage_top_10000"], 2),
    }
    for lang, v in vocab.items()
}).T
display(summary)

print(f"\\nSpanish has {vocab['es']['types'] / vocab['en']['types']:.2f}x "
      "as many word types as English.")"""),
    code("""for name in ("validation", "test"):
    oov = stats["splits"][name]["word_oov"]
    print(f"{name:11s} OOV rate — EN {oov['en']['unk_rate']:.2%}   "
          f"ES {oov['es']['unk_rate']:.2%}")

print("\\nMost frequent Spanish words missing from the 32k word vocabulary:")
print([w for w, _ in stats["splits"]["test"]["word_oov"]["es"]["most_common_unk"][:15]])"""),
    code("""from nmt.viz.data_plots import plot_vocabulary_growth, plot_subword_effect

plot_vocabulary_growth(stats, ROOT / "reports" / "figures" / "data_vocabulary")
plot_subword_effect(stats, ROOT / "reports" / "figures" / "data_subwords")
Image(str(ROOT / "reports" / "figures" / "data_vocabulary.png"), width=900)"""),
    markdown("""## What this means for the model

| Observation | Consequence |
|---|---|
| Sentences are short (median ~6 words) | `max_length = 64` discards a negligible tail; batches can be capped by token count |
| Spanish has ~1.6x the types of English | subword vocabulary; report chrF2 alongside BLEU |
| ~40% of types are hapax | a modest 16k vocabulary, so rare entries are still updated often enough to learn |
| Many-to-many links | component-aware splitting, verified on every build |
"""),
]

# ---------------------------------------------------------------------------
# 02 — preprocessing
# ---------------------------------------------------------------------------

NB02 = [
    markdown("""# 2 — Preprocessing and tokenisation

Every rule is a modelling decision. This notebook walks through each one on
real sentences, so the effect is visible rather than asserted."""),
    code(BOOTSTRAP),
    markdown("""## Normalisation

Order matters. NFC composition first (so accents unify), then control-character
removal (before whitespace collapsing, so stripping one cannot weld two words
together), then typographic folding, then whitespace."""),
    code("""from nmt.data.cleaning import normalise

examples = [
    "espan\\u0303ol",            # decomposed n + combining tilde
    "espa\\u00f1ol",             # pre-composed n-with-tilde
    "don\\u2019t  stop",         # curly apostrophe + double space
    "\\u201cquoted\\u201d text",  # curly quotes
    "dash\\u2014here",           # em dash
    "  ragged\\tspacing\\n",
]
for raw in examples:
    print(f"{raw!r:32s} -> {normalise(raw)!r}")

print("\\nThe two spellings of 'español' are different strings:",
      "espan\\u0303ol" != "espa\\u00f1ol")
print("...but normalise to the same one:",
      normalise("espan\\u0303ol") == normalise("espa\\u00f1ol"))"""),
    markdown("""### Casing and punctuation are deliberately preserved

Lowercasing would shrink the vocabulary and usually buys a point of BLEU, but
it makes the system unable to produce correctly-cased output — and the
deliverable is an application whose output a human reads. Spanish `¿` and `¡`
are grammatical signal."""),
    markdown("## Filtering"),
    code("""from nmt.data.cleaning import CleaningRules, clean_pairs

candidates = [
    ("Hello there.", "Hola."),
    ("", "Vac\\u00edo."),
    ("1997.", "1997."),
    ("Visit http://example.com", "Visita http://example.com"),
    ("Tom", "Tom"),
    ("Yes.", "S\\u00ed, lo har\\u00e9 pronto."),
    ("I am very tired today",
     "Estoy muy cansado hoy porque he trabajado toda la noche sin descansar "
     "ni un solo momento de verdad"),
]
kept, report = clean_pairs(candidates, CleaningRules())

print("kept:")
for pair in kept:
    print("  ", pair)
print("\\nremoved:", dict(report.removed))"""),
    markdown("""Note that `("Yes.", "Sí, lo haré pronto.")` **survives** despite a 1:4 length
ratio. The ratio filter is suppressed until both sides reach four tokens,
because short sentences legitimately have very different lengths."""),
    markdown("""## Component-aware splitting

The union-find structure merges every sentence that is transitively linked to
every other, then whole components are assigned to a split."""),
    code("""from nmt.data.splitting import SplitSizes, split_pairs

pairs = [
    ("I am tired.", "Estoy cansado."),
    ("I am tired.", "Estoy cansada."),
    ("Estoy cansado." , "I'm exhausted."),   # links back through the Spanish side
]
pairs = [(a, b) for a, b in pairs]
pairs += [(f"Sentence {i}.", f"Frase {i}.") for i in range(200)]

splits, report = split_pairs(pairs, SplitSizes(validation=0.1, test=0.1), seed=0)
print("sizes    :", report.split_pairs)
print("leakage  :", sum(report.leakage_check.values()))
print("components:", report.components)"""),
    markdown("""## Tokenisation

Two tokenisers, one interface. Both are fitted on the **training split only** —
fitting on the whole corpus would leak test-set surface forms into the
vocabulary and flatter the out-of-vocabulary rate we report."""),
    code("""from nmt.data.tokenizer import load_tokenizer
from nmt.constants import TAG_EN, TAG_ES

subword = load_tokenizer(ROOT / "artifacts" / "tokenizers" / "joint_bpe.model")
word = load_tokenizer(ROOT / "artifacts" / "tokenizers" / "word_vocab.json")

print("subword vocabulary:", f"{subword.vocab_size:,}")
print("word vocabulary   :", f"{word.vocab_size:,}")

sentence = "The internationalisation of unimaginably complicated vocabulary."
print("\\nsubword:", subword.tokenize(sentence))
print("\\nword   :", [word.id_to_piece(i) for i in word.encode(sentence)])"""),
    markdown("""The subword model splits an unseen long word into known pieces; the word-level
model maps it to `<unk>` and loses it permanently. That is the whole
trade-off."""),
    code("""# The reserved ids are pinned, and the direction tags survive as single tokens.
for piece in ("<pad>", "<unk>", "<s>", "</s>", TAG_EN, TAG_ES):
    print(f"{piece:8s} -> id {subword.piece_to_id(piece)}")

ids = subword.encode_source("I am tired.", TAG_ES)
print("\\nencoded source:", ids)
print("as pieces     :", [subword.id_to_piece(i) for i in ids])
print("round trip    :", subword.decode(ids))"""),
    markdown("""## Batching: token buckets, not fixed sentence counts

The length distribution is right-skewed, so a fixed sentence count produces
batches whose padding waste swings widely. Capping by *tokens* keeps memory per
step flat."""),
    code("""from nmt.data.build import read_split
from nmt.data.dataset import TranslationDataset, padding_waste

pairs = read_split(ROOT / "data" / "processed" / "validation.tsv")
dataset = TranslationDataset(pairs, subword)

print(f"{len(pairs):,} pairs -> {len(dataset):,} directional examples")
waste = padding_waste(dataset, max_tokens=8192)
for key, value in waste.items():
    print(f"  {key:20s} {value:,.3f}" if isinstance(value, float) else f"  {key:20s} {value:,}")"""),
    code("""# What a collated batch actually contains.
from nmt.data.dataset import collate_batch

batch = collate_batch([dataset[i] for i in range(4)])
print("source        ", tuple(batch.source.shape))
print("decoder_input ", tuple(batch.decoder_input.shape))
print("labels        ", tuple(batch.labels.shape))
print()
print("decoder_input[0]:", [subword.id_to_piece(i) for i in batch.decoder_input[0][:8].tolist()])
print("labels[0]       :", [subword.id_to_piece(i) for i in batch.labels[0][:8].tolist()])
print("\\nThe labels are the decoder input shifted left by one: position t predicts t+1.")"""),
]

# ---------------------------------------------------------------------------
# 03 — model walkthrough
# ---------------------------------------------------------------------------

NB03 = [
    markdown("""# 3 — The transformer, component by component

Every tensor shape in this notebook is printed, because shapes are where
seq2seq implementations go wrong."""),
    code(BOOTSTRAP),
    code("""import torch
from nmt.config import ModelConfig
from nmt.model.transformer import TranslationTransformer

torch.manual_seed(0)
config = ModelConfig(vocab_size=16000)
model = TranslationTransformer(config).eval()

breakdown = model.parameter_breakdown()
for key, value in breakdown.items():
    print(f"{key:14s} {value:>12,}")"""),
    markdown("""## Masks

Two logically different things, and conflating them is a classic silent bug.
Throughout this project **`True` means "attend here"**."""),
    code("""from nmt.model.masking import causal_mask, decoder_mask, padding_mask
from nmt.constants import PAD_ID

tokens = torch.tensor([[5, 6, 7, 8, PAD_ID, PAD_ID]])

print("padding mask (batch, 1, 1, len):", tuple(padding_mask(tokens).shape))
print(padding_mask(tokens)[0, 0, 0].int().tolist())

print("\\ncausal mask 5x5:")
print(causal_mask(5).squeeze().int())

print("\\ncombined decoder mask, row 3 (may see keys 0..3, but 4-5 are padding):")
print(decoder_mask(tokens)[0, 0, 3].int().tolist())"""),
    markdown("""## Scaled dot-product attention

$$\\mathrm{Attention}(Q,K,V) = \\mathrm{softmax}\\!\\left(\\frac{QK^\\top}{\\sqrt{d_k}}\\right)V$$

Read it as a differentiable dictionary lookup: queries are compared against
keys by dot product, softmax turns the scores into weights, and the output is a
weighted blend of the values."""),
    code("""from nmt.model.attention import ScaledDotProductAttention

attention = ScaledDotProductAttention()
q = torch.randn(1, 1, 4, 64)
k = torch.randn(1, 1, 6, 64)
v = torch.randn(1, 1, 6, 64)

context, weights = attention(q, k, v)
print("query   ", tuple(q.shape))
print("key     ", tuple(k.shape))
print("context ", tuple(context.shape))
print("weights ", tuple(weights.shape), "  rows sum to", weights.sum(-1).flatten()[:4].tolist())"""),
    markdown("""### Why divide by $\\sqrt{d_k}$

The dot product of two $d_k$-dimensional unit-variance vectors has variance
$d_k$, so raw scores grow like $\\sqrt{d_k}$. Softmax over widely spread values
saturates, and its gradient $p(1-p)$ collapses to zero — the layer stops
learning."""),
    code("""import math

d_k = 64
q = torch.randn(1, 1, 1, d_k)
k = torch.randn(1, 1, 500, d_k)

raw = (q @ k.transpose(-2, -1))
scaled = raw / math.sqrt(d_k)

print(f"raw scores    : std {raw.std():.2f}, range [{raw.min():.1f}, {raw.max():.1f}]")
print(f"scaled scores : std {scaled.std():.2f}, range [{scaled.min():.1f}, {scaled.max():.1f}]")

for name, scores in (("raw", raw), ("scaled", scaled)):
    p = torch.softmax(scores, -1)
    entropy = -(p * (p + 1e-12).log()).sum(-1).item()
    print(f"{name:7s}: max weight {p.max():.3f}, entropy {entropy:.2f} nats "
          f"(uniform would be {math.log(500):.2f})")"""),
    markdown("""## Multi-head attention

One softmax attends to essentially one place. Translating "the red house" as
"la casa roja" needs the noun tracked for gender agreement *and* the adjective
tracked for reordering, at the same time."""),
    code("""from nmt.model.attention import MultiHeadAttention

mha = MultiHeadAttention(512, 8)
x = torch.randn(2, 10, 512)

split = mha._split_heads(x)
print("input          ", tuple(x.shape))
print("after split    ", tuple(split.shape), " <- (batch, heads, len, d_k)")
print("after merge    ", tuple(mha._merge_heads(split).shape))
print("output         ", tuple(mha(x, x, x).shape))
print("\\nThe split is a reshape, so h heads cost the same as one.")"""),
    markdown("## Positional encoding"),
    code("""from nmt.model.positional import SinusoidalPositionalEncoding

pe = SinusoidalPositionalEncoding(128, max_length=100, dropout=0.0)
table = pe.encoding[0]

print("table shape:", tuple(table.shape))

# Relative position is a linear function of absolute position: the dot product
# between two encodings depends only on their distance apart.
for offset in (1, 2, 5, 10, 20):
    sims = [torch.dot(table[p], table[p + offset]).item() for p in range(10, 40)]
    print(f"offset {offset:2d}: dot product {sum(sims)/len(sims):8.2f} "
          f"(std {torch.tensor(sims).std():.3f})")"""),
    markdown("""The dot product depends almost entirely on the *distance* and barely on the
absolute position — which is what lets attention learn "look three tokens back"
as a single linear map that works everywhere."""),
    markdown("## The whole model, and the two invariants that must hold"),
    code("""source = torch.randint(4, 16000, (2, 9))
target = torch.randint(4, 16000, (2, 7))

logits = model(source, target)
print("source", tuple(source.shape), "target", tuple(target.shape), "-> logits", tuple(logits.shape))"""),
    code("""# INVARIANT 1: the decoder must not see the future.
with torch.no_grad():
    before = model(source, target)
    perturbed = target.clone()
    perturbed[:, 4] = 12345
    after = model(source, perturbed)

print("max change at positions BEFORE the edit:", (before[:, :4] - after[:, :4]).abs().max().item())
print("max change at positions AFTER  the edit:", (before[:, 4:] - after[:, 4:]).abs().max().item())
print("\\nThe first must be exactly 0. If it is not, the model is being handed the answer.")"""),
    code("""# INVARIANT 2: a sentence's translation must not depend on its batch-mates.
with torch.no_grad():
    base = model(source, target)
    padded = torch.cat([source, torch.zeros(2, 6, dtype=torch.long)], dim=1)
    extended = model(padded, target)

print("max change from six extra padding columns:", (base - extended).abs().max().item())
print("(float32 round-off only — around 1e-6.)")"""),
    markdown("## Where the parameters live"),
    code("""import pandas as pd

rows = []
for name, count in model.parameter_breakdown().items():
    if name in ("total", "trainable"):
        continue
    rows.append({"component": name, "parameters": count,
                 "share": count / model.parameter_breakdown()["total"]})
df = pd.DataFrame(rows).sort_values("parameters", ascending=False)
df["share"] = (100 * df["share"]).round(1).astype(str) + "%"
display(df)

print("\\nThe embedding table is shared three ways (encoder input, decoder input,")
print("output projection), so it is counted once. Untying it would add ~17M parameters.")"""),
]

# ---------------------------------------------------------------------------
# 04 — Colab training
# ---------------------------------------------------------------------------

NB04 = [
    markdown("""# 4 — Training on Google Colab

Runs the same `nmt.training.train` entry point used locally, on a GPU runtime.

**Before running:** Runtime → Change runtime type → **T4 GPU** (or better).

The primary model (`bpe_scratch`) sees 271k pairs → **543k directional
examples**, about 12M source+target tokens per epoch, through a 37.6M-parameter
model.

| Stage | T4 estimate |
|---|---|
| Download + build corpus | ~5 min |
| One training epoch | ~8–15 min |
| Full run (early stopping usually fires around epoch 10–14) | ~2–3 h |
| Test-set evaluation (beam 4, both directions) | ~10–15 min |

For reference, the same epoch takes **~3.4 hours** on an M-series MacBook GPU
(measured: ~1,030 tokens/s), which is why training runs here rather than
locally.

### Train in priority order

Colab free sessions are time-limited, so train in the order that protects the
most marks if you run out:

1. **`bpe_scratch`** — the primary model. Everything downstream needs it: the
   error analysis, the app, most of the report.
2. **`word_random` + `word_muse`** — train these two *as a pair* or not at all.
   `word_muse` alone proves nothing; `word_random` is the control that makes it
   interpretable.
3. **`lstm_baseline`** — the architecture comparison. Slowest per epoch,
   because its decoder has an explicit Python time loop.
"""),
    code("""# 1. Check the GPU
!nvidia-smi --query-gpu=name,memory.total --format=csv"""),
    code("""# 2. Clone the repository
#    Change this only if you are working from a fork.
REPO = "https://github.com/jolusano/en-es-transformer-nmt.git"

import os
if not os.path.exists("en-es-transformer-nmt"):
    !git clone $REPO en-es-transformer-nmt
%cd en-es-transformer-nmt
!ls"""),
    code("""# 3. Install the dependencies Colab does not already have
!pip install -q sentencepiece sacrebleu

import torch
print("torch", torch.__version__, "| CUDA", torch.cuda.is_available())"""),
    code("""# 4. Mount Drive so checkpoints survive a disconnect
from google.colab import drive
drive.mount("/content/drive")

CHECKPOINT_DIR = "/content/drive/MyDrive/aig230_nmt/checkpoints"
RESULTS_DIR = "/content/drive/MyDrive/aig230_nmt/results"
!mkdir -p "$CHECKPOINT_DIR" "$RESULTS_DIR"

# Symlink so the code writes straight to Drive without any config change.
!rm -rf artifacts/checkpoints artifacts/results
!mkdir -p artifacts
!ln -s "$CHECKPOINT_DIR" artifacts/checkpoints
!ln -s "$RESULTS_DIR" artifacts/results
!ls -la artifacts/"""),
    code("""# 5. Build the corpus (~5 min, downloads 172 MB)
!PYTHONPATH=src python -m nmt.data.build"""),
    code("""# 6. Verify the pipeline before spending GPU hours on it
!PYTHONPATH=src python -m nmt.training.train --config configs/smoke.yaml"""),
    markdown("""## Train the primary model

If the session disconnects, re-run the cells above and then add
`--resume artifacts/checkpoints/bpe_scratch/last.pt` — checkpoints carry the
optimiser and scheduler state, so training continues rather than restarting the
warmup."""),
    code("""!PYTHONPATH=src python -m nmt.training.train --config configs/bpe_scratch.yaml"""),
    markdown("""## The other three systems

`word_muse` needs the MUSE vectors (~1.3 GB); skip that cell if you only want
the architecture comparison."""),
    code("""# Pre-trained cross-lingual vectors (only needed for word_muse)
!mkdir -p data/raw/embeddings
!wget -q --show-progress -O data/raw/embeddings/wiki.multi.en.vec https://dl.fbaipublicfiles.com/arrival/vectors/wiki.multi.en.vec
!wget -q --show-progress -O data/raw/embeddings/wiki.multi.es.vec https://dl.fbaipublicfiles.com/arrival/vectors/wiki.multi.es.vec
!PYTHONPATH=src python -m nmt.data.embeddings"""),
    code("""for config in ["word_random", "word_muse", "lstm_baseline"]:
    print(f"\\n{'=' * 60}\\n{config}\\n{'=' * 60}")
    !PYTHONPATH=src python -m nmt.training.train --config configs/{config}.yaml"""),
    markdown("## Evaluate everything"),
    code("""import os

for run in ["bpe_scratch", "word_random", "word_muse", "lstm_baseline"]:
    checkpoint = f"artifacts/checkpoints/{run}/best_bleu.pt"
    if os.path.exists(checkpoint):
        print(f"\\n=== {run} ===")
        !PYTHONPATH=src python -m nmt.evaluation.evaluate --checkpoint {checkpoint}"""),
    code("""# Regenerate the figures and the report tables from the fresh results
!PYTHONPATH=src python -m nmt.viz.make_figures
!PYTHONPATH=src python reports/build_report_data.py

import json
from pathlib import Path

for path in sorted(Path("artifacts/results").glob("*/evaluation_test.json")):
    report = json.loads(path.read_text())
    print(f"{path.parent.name:16s} "
          f"EN->ES {report['summary']['bleu']['en-es']:6.2f}   "
          f"ES->EN {report['summary']['bleu']['es-en']:6.2f}")"""),
    code("""# Package the artefacts the report needs so they can be downloaded in one file
!zip -qr results.zip artifacts/results reports/figures reports/final_report/generated
from google.colab import files
files.download("results.zip")"""),
]

# ---------------------------------------------------------------------------
# 05 — evaluation and error analysis
# ---------------------------------------------------------------------------

NB05 = [
    markdown("""# 5 — Evaluation and error analysis

Requires a trained checkpoint and its `evaluation_test.json`:

```bash
python -m nmt.evaluation.evaluate --checkpoint artifacts/checkpoints/bpe_scratch/best_bleu.pt
```
"""),
    code(BOOTSTRAP),
    code("""# Prefer the primary model, but fall back to whatever has been evaluated so
# far, so the notebook is useful before the full runs have finished.
PREFERRED = "bpe_scratch"

available = sorted(
    p.parent.name
    for p in (ROOT / "artifacts" / "results").glob("*/evaluation_test.json")
)
if not available:
    raise SystemExit(
        "No evaluation results found. Train and evaluate a model first:\\n"
        "  python -m nmt.training.train --config configs/bpe_scratch.yaml\\n"
        "  python -m nmt.evaluation.evaluate "
        "--checkpoint artifacts/checkpoints/bpe_scratch/best_bleu.pt"
    )

RUN = PREFERRED if PREFERRED in available else available[0]
print("available runs:", available)
print("inspecting    :", RUN)

report = read_json(ROOT / "artifacts" / "results" / RUN / "evaluation_test.json")
print("checkpoint:", report["checkpoint"])
print("split     :", report["split"], f"({report['pairs']:,} pairs)")
print("decoding  :", report["decoding"])
print()
for direction, values in report["summary"]["bleu"].items():
    chrf = report["summary"]["chrf2"][direction]
    print(f"  {direction}   BLEU {values:6.2f}   chrF2 {chrf:6.2f}")"""),
    markdown("""## Our BLEU against sacreBLEU

We implement BLEU from the definition as course material, but quote sacreBLEU
in the report because BLEU is famously sensitive to tokenisation. They must
agree."""),
    code("""for direction in ("en-es", "es-en"):
    metrics = report["directions"][direction]["metrics"]
    ours = metrics["from_scratch"]["score"]
    theirs = metrics["sacrebleu"]["bleu"]
    print(f"{direction}: ours {ours:.4f}   sacrebleu {theirs:.4f}   "
          f"difference {abs(ours - theirs):.5f}")
print("\\nsignature:", report["directions"]["en-es"]["metrics"]["sacrebleu"]["signature"])"""),
    markdown("## Greedy against beam search"),
    code("""if "greedy_bleu" in report:
    import pandas as pd
    rows = []
    for direction in ("en-es", "es-en"):
        rows.append({
            "direction": direction,
            "greedy": round(report["greedy_bleu"][direction], 2),
            "beam": round(report["summary"]["bleu"][direction], 2),
            "gain": round(report["beam_gain"][direction], 2),
        })
    display(pd.DataFrame(rows))"""),
    markdown("""## Quality against sentence length

The claim being tested: a recurrent model carries information across a number
of sequential steps proportional to sentence length, whereas in a transformer
every pair of positions is one attention hop apart — so the recurrent model
should degrade faster on long inputs."""),
    code("""import pandas as pd

frames = []
for direction in ("en-es", "es-en"):
    buckets = report["directions"][direction]["error_analysis"]["bleu_by_length"]
    frame = pd.DataFrame(buckets)[["bucket", "sentences", "mean_sentence_bleu", "mean_length_ratio"]]
    frame["direction"] = direction
    frames.append(frame)
display(pd.concat(frames).round(2))"""),
    markdown("## Failure-mode census"),
    code("""for direction in ("en-es", "es-en"):
    analysis = report["directions"][direction]["error_analysis"]
    print(f"\\n=== {direction} ({analysis['sentences']:,} sentences) ===")
    for name, rate in sorted(analysis["category_rates"].items(), key=lambda x: -x[1]):
        count = analysis["category_counts"][name]
        print(f"  {name:22s} {count:6,}  ({rate:5.1%})")"""),
    markdown("""## The twenty worst translations

The detectors are a reading aid, not a verdict — read the examples and judge
each one. Some `no_content_overlap` cases are legitimate paraphrases that BLEU
simply cannot see."""),
    code("""for direction in ("en-es", "es-en"):
    print(f"\\n{'=' * 78}\\n{direction}\\n{'=' * 78}")
    for i, example in enumerate(report["directions"][direction]["error_analysis"]["worst"][:20], 1):
        print(f"\\n{i:2d}. sBLEU {example['sentence_bleu']:.1f}   [{', '.join(example['categories'])}]")
        print(f"    source : {example['source']}")
        print(f"    ref    : {example['reference']}")
        print(f"    model  : {example['hypothesis']}")"""),
    markdown("""## And what it gets right

A report that only shows failures gives no sense of what the system does
well."""),
    code("""for direction in ("en-es", "es-en"):
    print(f"\\n=== {direction} ===")
    for example in report["directions"][direction]["error_analysis"]["best"][:8]:
        print(f"  {example['source']}")
        print(f"    -> {example['hypothesis']}")"""),
    markdown("## Comparing every system"),
    code("""from nmt.viz.results_plots import load_reports, RUN_LABELS

reports = load_reports(ROOT / "artifacts" / "results")
rows = []
for name, r in reports.items():
    rows.append({
        "system": RUN_LABELS.get(name, name),
        "BLEU en-es": round(r["summary"]["bleu"]["en-es"], 2),
        "BLEU es-en": round(r["summary"]["bleu"]["es-en"], 2),
        "chrF2 en-es": round(r["summary"]["chrf2"]["en-es"], 2),
        "chrF2 es-en": round(r["summary"]["chrf2"]["es-en"], 2),
        "mean BLEU": round(r["summary"]["mean_bleu"], 2),
    })
display(pd.DataFrame(rows).sort_values("mean BLEU", ascending=False))"""),
]

# ---------------------------------------------------------------------------
# 06 — attention
# ---------------------------------------------------------------------------

NB06 = [
    markdown("""# 6 — What the model attends to

Cross-attention weights are the closest thing a transformer has to an explicit
word alignment. They are also a genuinely useful debugging tool: a diffuse,
structureless map usually means the model has collapsed to a language-model
prior and is ignoring the source."""),
    code(BOOTSTRAP),
    code("""import torch
from nmt.inference.search import DecodeConfig
from nmt.inference.translator import Translator

PREFERRED = ROOT / "artifacts" / "checkpoints" / "bpe_scratch" / "best_bleu.pt"

if PREFERRED.exists():
    CHECKPOINT = PREFERRED
else:
    candidates = sorted((ROOT / "artifacts" / "checkpoints").glob("*/best_bleu.pt"))
    if not candidates:
        raise SystemExit(
            "No checkpoint found. Train a model first:\\n"
            "  python -m nmt.training.train --config configs/bpe_scratch.yaml"
        )
    CHECKPOINT = candidates[0]
    print(f"{PREFERRED.parent.name} not trained yet; using {CHECKPOINT.parent.name} "
          "-- its translations will be poor.")

translator = Translator.from_checkpoint(
    CHECKPOINT, decode_config=DecodeConfig(strategy="beam", beam_size=4)
)
print("device    :", translator.device)
print("vocabulary:", f"{translator.tokenizer.vocab_size:,}")"""),
    markdown("## A first translation, both ways"),
    code("""for sentence, direction in [
    ("The red house on the corner belongs to my grandmother.", "en-es"),
    ("No s\\u00e9 si podr\\u00e9 ir a la fiesta ma\\u00f1ana.", "es-en"),
]:
    result = translator.translate(sentence, direction)
    print(f"[{direction}] {sentence}")
    print(f"       -> {result.translation}")
    print(f"          ({result.num_source_tokens} source tokens, "
          f"{result.num_output_tokens} generated, {result.seconds * 1000:.0f} ms)\\n")"""),
    markdown("""## The alignment

The orange box on each row marks the source position the model attended to most
while generating that token. English–Spanish adjective/noun reordering ("red
house" → "casa roja") should show up as a crossing in the diagonal."""),
    code("""from nmt.viz.attention_plots import plot_alignment
from IPython.display import Image

SENTENCE, DIRECTION = "The red house is very big.", "en-es"

result = translator.translate(SENTENCE, DIRECTION, return_attention=True)
print(result.translation)

out = ROOT / "reports" / "figures" / "attention_alignment"
plot_alignment(
    result.attention, result.source_tokens, result.output_tokens, out,
    title=f"Cross-attention: {SENTENCE}",
    subtitle="averaged over heads and layers",
)
Image(str(out.with_suffix(".png")), width=800)"""),
    markdown("""## Individual heads specialise

Averaging hides the structure. Different heads pick up different jobs — one
tracks the previous token, another the sentence boundary, another the aligned
content word — and the mean of eight such heads looks blander than any of
them."""),
    code("""from nmt.viz.attention_plots import plot_head_grid

# Re-run storing attention, then take the last decoder layer's cross-attention.
source = torch.tensor([translator._encode_source(SENTENCE, DIRECTION)],
                      device=translator.device)
generated = torch.tensor([[translator.tokenizer.piece_to_id(p)
                           for p in result.output_tokens]], device=translator.device)

with torch.no_grad():
    translator.model(source, generated[:, :-1], store_attention=True)

cross = translator.model.attention_maps()["cross"]
print(f"{len(cross)} decoder layers, each {tuple(cross[0].shape)} "
      "= (batch, heads, target_len, source_len)")

out = ROOT / "reports" / "figures" / "attention_heads"
plot_head_grid(
    cross[-1][0], result.source_tokens, result.output_tokens[:-1], out,
    title="Cross-attention per head, final decoder layer",
)
Image(str(out.with_suffix(".png")), width=900)"""),
    markdown("## Attention sharpens with depth"),
    code("""from nmt.viz.attention_plots import plot_layer_progression

out = ROOT / "reports" / "figures" / "attention_layers"
plot_layer_progression(
    [layer[0] for layer in cross],
    result.source_tokens, result.output_tokens[:-1], out,
)
Image(str(out.with_suffix(".png")), width=900)"""),
    markdown("""The mean entropy printed under each panel quantifies it: a lower value means
the distribution is more concentrated, i.e. the decoder has committed to a
specific source position."""),
    markdown("""## Decoding settings, live

Beam search usually buys 1–2 BLEU. The length penalty matters more than it
looks: without it, beam search systematically truncates, because every
log-probability is negative and longer hypotheses accumulate a worse score just
for being longer."""),
    code("""SENTENCE = "She has been studying Spanish for three years and can now hold a conversation."

for strategy, beam, penalty in [
    ("greedy", 1, 0.0),
    ("beam", 4, 0.0),
    ("beam", 4, 0.6),
    ("beam", 8, 0.6),
    ("beam", 4, 1.2),
]:
    translator.decode_config = DecodeConfig(
        strategy=strategy, beam_size=beam, length_penalty=penalty
    )
    result = translator.translate(SENTENCE, "en-es")
    label = f"{strategy}" + (f" b={beam} a={penalty}" if strategy == "beam" else "")
    print(f"{label:18s} ({result.num_output_tokens:2d} tok) {result.translation}")"""),
    markdown("## Where it breaks"),
    code("""translator.decode_config = DecodeConfig(strategy="beam", beam_size=4, length_penalty=0.6)

hard = [
    ("Tom bought a Volkswagen in Saskatchewan.", "en-es"),   # rare proper nouns
    ("I have 1,234 books and 56 magazines.", "en-es"),        # numbers
    ("The man who the woman that I saw yesterday met is my brother.", "en-es"),  # nesting
    ("Se lo di\\u00f3.", "es-en"),                                  # clitics, ambiguous
    ("\\u00a1Qu\\u00e9 fr\\u00edo hace hoy!", "es-en"),                          # exclamative
]
for sentence, direction in hard:
    result = translator.translate(sentence, direction)
    print(f"[{direction}] {sentence}\\n       -> {result.translation}\\n")"""),
]

# ---------------------------------------------------------------------------

NOTEBOOKS = {
    "01_data_exploration.ipynb": NB01,
    "02_preprocessing.ipynb": NB02,
    "03_model_walkthrough.ipynb": NB03,
    "04_training_colab.ipynb": NB04,
    "05_evaluation_and_errors.ipynb": NB05,
    "06_attention_visualisation.ipynb": NB06,
}


def main() -> None:
    for name, cells in NOTEBOOKS.items():
        path = HERE / name
        path.write_text(
            json.dumps(notebook(cells), indent=1, ensure_ascii=False) + "\n",
            encoding="utf-8",
        )
        print(f"wrote {path.relative_to(HERE.parent)}  ({len(cells)} cells)")


if __name__ == "__main__":
    main()
